Archive Carousel for desktop and mobile
acm-uic/flourish-2023 pull request #84
Opened 2022-10-30 23:02 UTC by rapterjet2004

Fixes #73 
Fixes #74 

Sorry for the late PR, had midterms all of last week. Decided to knock out two birds with one stone on this one. 

- There is a carousel that rotates through images, titles, descriptions, and links every 5 seconds
- The following pictures/description/titles/link are available
- It should span the width of the page
- The user should be able to click through them
- It should use proper font sizing, coloring
- The background image should be darkened
- The images should be locally available
- Responsive, carousel css adjusts for mobile devices (I made sure to use the same bounds as tailwindcss, which is 640px width to indicate small devices. I didn't include anything for tablet screens b/c the format looked alright as is)
- Scalable, to add a new slide, simply add a new image to /assets/images/archiveImages, and then modify the list in ArchiveCarousel/allarchive.jsx to match and the code does the rest
- I also downloaded two (free and transparent) chevron arrow icons for the carousel and included them under assets/icons/

Also went ahead and made the WhoWeAreSection a component and fixed some minor formatting bugs in the Description component that was affecting my carousel on mobile.

2022-10-30 23:35 UTC, rapterjet2004 commented on src/components/Description/index.jsx
> +                    <div className={"text-center sm:mx-[5rem] sm:min-w-full sm:text-left"}>
Don't know why this is showing up as changed, I reverted my prior commit, this should be unchanged file

2022-11-05 00:56 UTC, ChristianBingman requested changes
Needs a little more changes, few major notes, class is invalid in react since class is reserved in JS, but you are writing inline HTML essentially. I will be upping the estimate on this, I really appreciate all the work on this!

2022-11-05 00:56 UTC, ChristianBingman commented on src/pages/about.js
> +import WhoWeAreSection from '../components/WhoAreWeSection';
Could you call it WhoAreWe instead of WhoAreWeSection

2022-11-05 00:56 UTC, ChristianBingman commented on src/components/ArchiveCarousel/index.jsx
> +      <h1 class="grid place-items-center">Archive</h1>
Class is invalid JSX, use classname

2022-11-05 00:56 UTC, ChristianBingman commented on src/components/ArchiveCarousel/index.jsx
> +      <button className="indicatorLeft" onClick={() => {
Could you remove the indicators on mobile?

2022-11-05 00:56 UTC, ChristianBingman commented on src/components/ArchiveCarousel/archivecarousel.css
> +.carousel{
Most of these can be implemented in tailwind

2022-11-05 00:56 UTC, ChristianBingman commented on src/components/ArchiveCarousel/Item/index.jsx
> +        {matches && (<h1 class="title" >{props.title}</h1>)}
class is invalid jsx

2022-11-05 00:56 UTC, ChristianBingman commented on src/components/ArchiveCarousel/Item/item.css
> +    color: yellow;
The link color is secondary dark iirc

2022-11-05 22:57 UTC, rapterjet2004 commented
Got it, I
- deleted the css files and used tailwind instead
- changed the website link color to secondary dark
- changed all class keywords to className
- renamed WhoAreWeSection to just WhoAreWe

2022-11-05 23:18 UTC, ChristianBingman commented on src/pages/about.js
> +import WhoWeAreSection from '../components/WhoAreWeSection';
It should be WhoAreWe, much better for consistency.

2022-11-05 23:20 UTC, ChristianBingman requested changes
Very very close, could you fix the naming of WhoAreWe for consistency, and there was a new error in the [build](https://github.com/acm-uic/flourish-2023/actions/runs/3401983003/jobs/5657440283#step:3:43) (You can ignore the prop-type errors for now.

2022-11-05 23:40 UTC, ChristianBingman commented on src/components/ArchiveCarousel/index.jsx
> +            return <Item key={c} name={c[0]} title={c[1]} description={c[2]} link={c[3]}/>
Not a great key, but that'll work

2022-11-05 23:40 UTC, ChristianBingman approved these changes
Great thanks!

2022-11-05 23:41 UTC, merged